import 'package:hcms/model/record.dart';
import 'package:hcms/utils/time_util.dart';

class RecordState {
  late List<RoomRecord> recordList;

  RecordState() {
    recordList = [
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
      RoomRecord(
          id: 0,
          roomNum: 301,
          roomType: "宾馆",
          payType: "实收",
          currencyUnit: "宽扎",
          livingDays: 1,
          price: 1000,
          amountPrice: 5000,
          transType: "现金",
          realPayAmount: 1000,
          date: DateTime.now().millisecondsSinceEpoch,
          remark: ""),
    ];
  }
}
